# Dockerdeploy
## VARIABLES
USER=root
HOST_IP=10.0.2.4 
BUILD_DIRECTORY="/root/builds/projectX"
DEPLOY_MODULE="deployTools/projectX"
CONFIG_MODULE="projectX/config"
WORKSPACE="/var/jenkins_home/workspace/"
REPO_NAME="ameyrk/tomcat"

## CREATING BUILD DIRECTORY
ssh $USER@$HOST_IP "mkdir -p $BUILD_DIRECTORY"

## COPY NECESSARY FILES TO BUILD YOUR CONATAINER
scp $WORKSPACE$JOB_NAME/$CONFIG_MODULE/* $USER@$HOST_IP:$BUILD_DIRECTORY
scp $WORKSPACE$JOB_NAME/$DEPLOY_MODULE/* $USER@$HOST_IP:$BUILD_DIRECTORY

## BUILD CONTAINER, PUSH CONTAINER INTO REPOSITORY & DELETE LOCAL COPY OF YOUR CONTAINER
cd $DEPLOY_MODULE 
ssh $USER@$HOST_IP "bash -s" < ./deploy.sh $REPO_NAME $BUILD_DIRECTORY $BUILD_NUMBER
